# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('bookmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reviews',
            managers=[
                ('bookmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
