# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170205_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
